import Footer from "@/components/headers/footer/Footer";
import "./globals.css";

export const metadata = {
  title: "StreamLine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
