import "./globals.css";
import Link from "next/link";
export const metadata = {
  title: "StreamLine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>
            <Link href="/about">About</Link>
          </h1>
          <h1>
            <Link href="/discover">Discover</Link>
          </h1>
        </header>
        {children}
      </body>
    </html>
  );
}
